name: Your Workflow Name

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Print Current Directory
        run: |
          pwd

      - name: Azure Kubernetes Service
        uses: azure/k8s-deploy@v4
        with:
          action: deploy
          manifests: "src/**"
          azureCredentials: ${{ secrets.AZURE_CREDENTIALS }}
