# deployment1.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app1
  template:
    metadata:
      labels:
        app: app1
    spec:
      containers:
      - name: app-container
        image: your-image1:tag
