name: DEV

on:
  push:
    branches:
      - main
    # paths:
    #   - './**'
    #   - '.github/workloads/dev/**'

permissions:
  id-token: write
  contents: read

jobs:
  Deploy:
    runs-on: ubuntu-latest
    environment: "dev-azure"

    steps:
      - name: Get application k8s manifests from repo
        uses: actions/checkout@v2

      - name: Azure Login
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Install Kubectl
        uses: azure/setup-kubectl@v3.0
        with:
          version: 'latest'

      - name: Set the target Azure Kubernetes Service (AKS) cluster.
        uses: azure/aks-set-context@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          cluster-name: "aks-free-eastus-1"
          resource-group: ${{ secrets.RESOURCE_GROUP }}

      - name: Set environment variable
        env:
          ACRNAME: ${{ secrets.REGISTRY_LOGIN_SERVER }}
        run: |
          export ACRNAME

      - name: Azure Kubernetes Service
        uses: azure/k8s-deploy@v4
        with:
          action: deploy
          manifests: |
            ".github/workloads/1.yaml"
            ".github/workloads/2.yaml"
            ".github/workloads/3.yaml"


        
        
     

            
