name: Copy Secrets to Key Vault

on:
  push:
    branches:
      - main

jobs:
  copy-secrets:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Azure CLI
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Check and update Azure CLI
        run: |
          az --version
          az extension add --name azure-cli-iot-ext

      - name: Get list of secrets from source Key Vault
        id: get-secrets
        run: |
          SOURCE_KEYVAULT="kv-free-eastus-1"
          SECRETS=($(az keyvault secret list --vault-name $SOURCE_KEYVAULT --query "[].id" -o tsv))
          echo "::set-output name=secrets::${SECRETS[*]}"

      - name: Copy secrets to destination Key Vault
        id: copy-secrets
        run: |
          DESTINATION_KEYVAULT="my-transfredvault"
          for SECRET in "${{ steps.get-secrets.outputs.secrets }}"; do
            SECRETNAME=$(echo "$SECRET" | sed 's|.*/||')
            SECRET_CHECK=$(az keyvault secret list --vault-name $DESTINATION_KEYVAULT --query "[?name=='$SECRETNAME']" -o tsv)

            if [ -n "$SECRET_CHECK" ]; then
              echo "A secret with name $SECRETNAME already exists in $DESTINATION_KEYVAULT"
            else
              echo "Copying $SECRETNAME to KeyVault: $DESTINATION_KEYVAULT"
              SECRET=$(az keyvault secret show --vault-name $SOURCE_KEYVAULT -n $SECRETNAME --query "value" -o tsv)
              az keyvault secret set --vault-name $DESTINATION_KEYVAULT -n $SECRETNAME --value "$SECRET" >/dev/null || exit 1
            fi
          done
