# deployment2.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment2
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app2
  template:
    metadata:
      labels:
        app: app2
    spec:
      containers:
      - name: app-container
        image: your-image2:tag
