apiVersion: apps/v1
kind: Deployment
metadata:
  name: tiktok
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tiktok
  template:
    metadata:
      labels:
        app: tiktok
    spec:
      nodeSelector:
        application: d4s
      containers:
      - name: tiktok
        image: nginx
        imagePullPolicy: Always
        ports:
        - containerPort: 8001
        resources:
          requests:
            cpu: 100m
            memory: 512Mi
          limits:
            cpu: 200m
            memory: 512MiMi       
---
apiVersion: v1
kind: Service
metadata:
  name: tiktok-service
spec:
  type: ClusterIP
  selector:
    app: tiktok
  ports:
  - port: 80
    targetPort: 8001